import type { FastifyPluginAsync } from 'fastify';
import { Type } from '@sinclair/typebox';
import { TaskPriority, TaskStatus } from '@prisma/client';
import { data, ensureWorkspaceUser, pageOf, paginated, parseDate, projectInWorkspace, sendNoContent, taskInWorkspace } from '../../common/http.js';
import { forbidden, notFound } from '../../common/errors/app-error.js';

const taskParams = Type.Object({ workspaceId: Type.String({ format: 'uuid' }), taskId: Type.String({ format: 'uuid' }) }, { additionalProperties: false });
const createBody = Type.Object({ projectId: Type.String({ format: 'uuid' }), title: Type.String({ minLength: 1, maxLength: 200 }), description: Type.Optional(Type.String({ maxLength: 5000 })), status: Type.Optional(Type.Enum(TaskStatus)), priority: Type.Optional(Type.Enum(TaskPriority)), assigneeId: Type.Optional(Type.Union([Type.String({ format: 'uuid' }), Type.Null()])), dueDate: Type.Optional(Type.Union([Type.String({ format: 'date-time' }), Type.Null()])), labelIds: Type.Optional(Type.Array(Type.String({ format: 'uuid' }), { uniqueItems: true, maxItems: 20 })) }, { additionalProperties: false });
const include = { assignee: { select: { id: true, name: true, avatarUrl: true } }, reporter: { select: { id: true, name: true, avatarUrl: true } }, labels: { include: { label: true } }, subtasks: { where: { deletedAt: null }, orderBy: { position: 'asc' as const } } };

const routes: FastifyPluginAsync = async (app) => {
  app.addHook('preHandler', app.authenticate);
  app.get('/', { schema: { tags: ['Tasks'], security: [{ bearerAuth: [] }], querystring: Type.Object({ page: Type.Optional(Type.Integer({ minimum: 1 })), limit: Type.Optional(Type.Integer({ minimum: 1, maximum: 100 })), search: Type.Optional(Type.String()), projectId: Type.Optional(Type.String({ format: 'uuid' })), assigneeId: Type.Optional(Type.String({ format: 'uuid' })), status: Type.Optional(Type.Enum(TaskStatus)), priority: Type.Optional(Type.Enum(TaskPriority)), labelId: Type.Optional(Type.String({ format: 'uuid' })), dueFrom: Type.Optional(Type.String({ format: 'date-time' })), dueTo: Type.Optional(Type.String({ format: 'date-time' })), sort: Type.Optional(Type.Union([Type.Literal('createdAt'), Type.Literal('updatedAt'), Type.Literal('dueDate'), Type.Literal('priority'), Type.Literal('position')])), order: Type.Optional(Type.Union([Type.Literal('asc'), Type.Literal('desc')])) }, { additionalProperties: false }) } }, async (request) => {
    const { id: workspaceId } = await app.requireWorkspace(request); const q = request.query as any; const { page, limit } = pageOf(q); const where: any = { workspaceId, deletedAt: null, parentTaskId: null, projectId: q.projectId, assigneeId: q.assigneeId, status: q.status, priority: q.priority, labels: q.labelId ? { some: { labelId: q.labelId } } : undefined, dueDate: q.dueFrom || q.dueTo ? { gte: parseDate(q.dueFrom), lte: parseDate(q.dueTo) } : undefined, OR: q.search ? [{ title: { contains: q.search, mode: 'insensitive' } }, { description: { contains: q.search, mode: 'insensitive' } }] : undefined };
    const [items, total] = await app.prisma.$transaction([app.prisma.task.findMany({ where, include, skip: (page - 1) * limit, take: limit, orderBy: { [q.sort ?? 'createdAt']: q.order ?? 'desc' } }), app.prisma.task.count({ where })]); return paginated(request, items, page, limit, total);
  });
  app.post('/', { schema: { tags: ['Tasks'], security: [{ bearerAuth: [] }], body: createBody } }, async (request, reply) => {
    const membership = await app.requireWorkspace(request, ['OWNER', 'ADMIN', 'MEMBER']); const body = request.body as any; await projectInWorkspace(app.prisma, membership.id, body.projectId); if (body.assigneeId) await ensureWorkspaceUser(app.prisma, membership.id, body.assigneeId);
    const position = await app.prisma.task.count({ where: { workspaceId: membership.id, projectId: body.projectId, status: body.status ?? 'TODO', deletedAt: null, parentTaskId: null } });
    const { labelIds, ...fields } = body; const task = await app.prisma.task.create({ data: { ...fields, workspaceId: membership.id, reporterId: request.authUser.id, dueDate: parseDate(body.dueDate), position, completedAt: body.status === 'DONE' ? new Date() : null, labels: labelIds ? { create: labelIds.map((labelId: string) => ({ labelId })) } : undefined }, include });
    await app.prisma.activity.create({ data: { workspaceId: membership.id, projectId: task.projectId, taskId: task.id, actorId: request.authUser.id, action: 'TASK_CREATED', metadata: { title: task.title } } }); return reply.code(201).send(data(request, task));
  });
  app.get('/:taskId', { schema: { tags: ['Tasks'], params: taskParams, security: [{ bearerAuth: [] }] } }, async (request) => { const { id } = await app.requireWorkspace(request); const task = await app.prisma.task.findFirst({ where: { id: (request.params as any).taskId, workspaceId: id, deletedAt: null }, include: { ...include, project: true, _count: { select: { comments: true, attachments: true } } } }); if (!task) throw notFound('Task'); return data(request, task); });
  app.patch('/:taskId', { schema: { tags: ['Tasks'], params: taskParams, security: [{ bearerAuth: [] }], body: Type.Partial(createBody) } }, async (request) => {
    const membership = await app.requireWorkspace(request, ['OWNER', 'ADMIN', 'MEMBER']); const { taskId } = request.params as any; const old = await taskInWorkspace(app.prisma, membership.id, taskId); const body = request.body as any; if (body.projectId) await projectInWorkspace(app.prisma, membership.id, body.projectId); if (body.assigneeId) await ensureWorkspaceUser(app.prisma, membership.id, body.assigneeId);
    const { labelIds, ...fields } = body; const task = await app.prisma.$transaction(async (tx) => { if (labelIds) { await tx.taskLabel.deleteMany({ where: { taskId } }); await tx.taskLabel.createMany({ data: labelIds.map((labelId: string) => ({ taskId, labelId })) }); } return tx.task.update({ where: { id: taskId }, data: { ...fields, dueDate: parseDate(body.dueDate), completedAt: body.status === 'DONE' ? old.completedAt ?? new Date() : body.status ? null : undefined }, include }); });
    const action = body.status && body.status !== old.status ? body.status === 'DONE' ? 'TASK_COMPLETED' : 'TASK_STATUS_CHANGED' : body.assigneeId !== undefined && body.assigneeId !== old.assigneeId ? 'TASK_ASSIGNEE_CHANGED' : null;
    if (action) await app.prisma.activity.create({ data: { workspaceId: membership.id, projectId: task.projectId, taskId, actorId: request.authUser.id, action, metadata: { fromStatus: old.status, toStatus: task.status, assigneeId: task.assigneeId } } }); return data(request, task);
  });
  app.delete('/:taskId', { schema: { tags: ['Tasks'], params: taskParams, security: [{ bearerAuth: [] }] } }, async (request, reply) => { const { id } = await app.requireWorkspace(request, ['OWNER', 'ADMIN', 'MEMBER']); const task = await taskInWorkspace(app.prisma, id, (request.params as any).taskId); await app.prisma.task.update({ where: { id: task.id }, data: { deletedAt: new Date() } }); return sendNoContent(reply); });
  app.patch('/:taskId/move', { schema: { tags: ['Tasks'], params: taskParams, security: [{ bearerAuth: [] }], body: Type.Object({ status: Type.Enum(TaskStatus), position: Type.Integer({ minimum: 0 }) }, { additionalProperties: false }) } }, async (request) => {
    const { id: workspaceId } = await app.requireWorkspace(request, ['OWNER', 'ADMIN', 'MEMBER']); const { taskId } = request.params as any; const body = request.body as any; const old = await taskInWorkspace(app.prisma, workspaceId, taskId);
    const moved = await app.prisma.$transaction(async (tx) => { await tx.$queryRaw`SELECT id FROM "Task" WHERE "projectId" = ${old.projectId}::uuid AND "deletedAt" IS NULL FOR UPDATE`; const targetCount = await tx.task.count({ where: { projectId: old.projectId, status: body.status, deletedAt: null, parentTaskId: null, id: { not: taskId } } }); const position = Math.min(body.position, targetCount); if (old.status === body.status) { if (position < old.position) await tx.task.updateMany({ where: { projectId: old.projectId, status: old.status, deletedAt: null, parentTaskId: null, position: { gte: position, lt: old.position }, id: { not: taskId } }, data: { position: { increment: 1 } } }); else await tx.task.updateMany({ where: { projectId: old.projectId, status: old.status, deletedAt: null, parentTaskId: null, position: { gt: old.position, lte: position }, id: { not: taskId } }, data: { position: { decrement: 1 } } }); } else { await tx.task.updateMany({ where: { projectId: old.projectId, status: old.status, deletedAt: null, parentTaskId: null, position: { gt: old.position } }, data: { position: { decrement: 1 } } }); await tx.task.updateMany({ where: { projectId: old.projectId, status: body.status, deletedAt: null, parentTaskId: null, position: { gte: position } }, data: { position: { increment: 1 } } }); } return tx.task.update({ where: { id: taskId }, data: { status: body.status, position, completedAt: body.status === 'DONE' ? old.completedAt ?? new Date() : null }, include }); }, { isolationLevel: 'Serializable' });
    if (old.status !== moved.status) await app.prisma.activity.create({ data: { workspaceId, projectId: old.projectId, taskId, actorId: request.authUser.id, action: moved.status === 'DONE' ? 'TASK_COMPLETED' : 'TASK_STATUS_CHANGED', metadata: { fromStatus: old.status, toStatus: moved.status } } }); return data(request, moved);
  });
  app.post('/:taskId/subtasks', { schema: { tags: ['Tasks'], params: taskParams, security: [{ bearerAuth: [] }], body: Type.Object({ title: Type.String({ minLength: 1, maxLength: 200 }), assigneeId: Type.Optional(Type.String({ format: 'uuid' })), dueDate: Type.Optional(Type.String({ format: 'date-time' })) }, { additionalProperties: false }) } }, async (request, reply) => { const { id } = await app.requireWorkspace(request, ['OWNER', 'ADMIN', 'MEMBER']); const parent = await taskInWorkspace(app.prisma, id, (request.params as any).taskId); if (parent.parentTaskId) throw forbidden('Nested subtasks are not supported'); const body = request.body as any; if (body.assigneeId) await ensureWorkspaceUser(app.prisma, id, body.assigneeId); const position = await app.prisma.task.count({ where: { parentTaskId: parent.id, deletedAt: null } }); const subtask = await app.prisma.task.create({ data: { ...body, workspaceId: id, projectId: parent.projectId, parentTaskId: parent.id, reporterId: request.authUser.id, dueDate: parseDate(body.dueDate), position } }); return reply.code(201).send(data(request, subtask)); });
  app.patch('/:taskId/subtasks/:subtaskId', { schema: { tags: ['Tasks'], security: [{ bearerAuth: [] }], params: Type.Object({ workspaceId: Type.String({ format: 'uuid' }), taskId: Type.String({ format: 'uuid' }), subtaskId: Type.String({ format: 'uuid' }) }), body: Type.Object({ title: Type.Optional(Type.String({ minLength: 1, maxLength: 200 })), status: Type.Optional(Type.Enum(TaskStatus)), assigneeId: Type.Optional(Type.Union([Type.String({ format: 'uuid' }), Type.Null()])), dueDate: Type.Optional(Type.Union([Type.String({ format: 'date-time' }), Type.Null()])) }, { additionalProperties: false }) } }, async (request) => { const { id } = await app.requireWorkspace(request, ['OWNER', 'ADMIN', 'MEMBER']); const p = request.params as any; const subtask = await app.prisma.task.findFirst({ where: { id: p.subtaskId, parentTaskId: p.taskId, workspaceId: id, deletedAt: null } }); if (!subtask) throw notFound('Subtask'); const body = request.body as any; return data(request, await app.prisma.task.update({ where: { id: subtask.id }, data: { ...body, dueDate: parseDate(body.dueDate), completedAt: body.status === 'DONE' ? new Date() : body.status ? null : undefined } })); });
};
export default routes;
