import type { FastifyPluginAsync } from 'fastify';
import { Type } from '@sinclair/typebox';
import { randomUUID } from 'node:crypto';
import { extname } from 'node:path';
import { data, pageOf, paginated, projectInWorkspace, sendNoContent, taskInWorkspace } from '../../common/http.js';
import { forbidden, notFound } from '../../common/errors/app-error.js';

const taskParams = Type.Object({ workspaceId: Type.String({ format: 'uuid' }), taskId: Type.String({ format: 'uuid' }) }, { additionalProperties: false });
const childParams = (name: string) => Type.Object({ workspaceId: Type.String({ format: 'uuid' }), taskId: Type.String({ format: 'uuid' }), [name]: Type.String({ format: 'uuid' }) }, { additionalProperties: false });
const commentBody = Type.Object({ body: Type.String({ minLength: 1, maxLength: 5000 }) }, { additionalProperties: false });

const routes: FastifyPluginAsync = async (app) => {
  app.addHook('preHandler', app.authenticate);
  app.get('/projects/:projectId/board', { schema: { tags: ['Tasks'], security: [{ bearerAuth: [] }], params: Type.Object({ workspaceId: Type.String({ format: 'uuid' }), projectId: Type.String({ format: 'uuid' }) }) } }, async (request) => { const { id } = await app.requireWorkspace(request); const { projectId } = request.params as any; const project = await projectInWorkspace(app.prisma, id, projectId); const tasks = await app.prisma.task.findMany({ where: { workspaceId: id, projectId, deletedAt: null, parentTaskId: null }, include: { assignee: { select: { id: true, name: true, avatarUrl: true } }, labels: { include: { label: true } }, _count: { select: { comments: true, attachments: true, subtasks: true } } }, orderBy: [{ status: 'asc' }, { position: 'asc' }] }); return data(request, { project, columns: ['BACKLOG', 'TODO', 'IN_PROGRESS', 'REVIEW', 'DONE'].map((status) => ({ status, tasks: tasks.filter((task) => task.status === status) })) }); });
  app.get('/tasks/:taskId/comments', { schema: { tags: ['Comments'], params: taskParams, security: [{ bearerAuth: [] }], querystring: Type.Object({ page: Type.Optional(Type.Integer({ minimum: 1 })), limit: Type.Optional(Type.Integer({ minimum: 1, maximum: 100 })) }, { additionalProperties: false }) } }, async (request) => { const { id } = await app.requireWorkspace(request); const { taskId } = request.params as any; await taskInWorkspace(app.prisma, id, taskId); const { page, limit } = pageOf(request.query as any); const where = { taskId, deletedAt: null }; const [items, total] = await app.prisma.$transaction([app.prisma.comment.findMany({ where, include: { author: { select: { id: true, name: true, avatarUrl: true } } }, orderBy: { createdAt: 'desc' }, skip: (page - 1) * limit, take: limit }), app.prisma.comment.count({ where })]); return paginated(request, items, page, limit, total); });
  app.post('/tasks/:taskId/comments', { schema: { tags: ['Comments'], params: taskParams, security: [{ bearerAuth: [] }], body: commentBody } }, async (request, reply) => { const { id } = await app.requireWorkspace(request, ['OWNER', 'ADMIN', 'MEMBER']); const task = await taskInWorkspace(app.prisma, id, (request.params as any).taskId); const comment = await app.prisma.comment.create({ data: { taskId: task.id, authorId: request.authUser.id, body: (request.body as any).body.trim() }, include: { author: { select: { id: true, name: true, avatarUrl: true } } } }); await app.prisma.activity.create({ data: { workspaceId: id, projectId: task.projectId, taskId: task.id, actorId: request.authUser.id, action: 'COMMENT_ADDED', metadata: { commentId: comment.id } } }); return reply.code(201).send(data(request, comment)); });
  app.patch('/tasks/:taskId/comments/:commentId', { schema: { tags: ['Comments'], params: childParams('commentId'), security: [{ bearerAuth: [] }], body: commentBody } }, async (request) => { const { id } = await app.requireWorkspace(request); const p = request.params as any; await taskInWorkspace(app.prisma, id, p.taskId); const comment = await app.prisma.comment.findFirst({ where: { id: p.commentId, taskId: p.taskId, deletedAt: null } }); if (!comment) throw notFound('Comment'); if (comment.authorId !== request.authUser.id) throw forbidden(); return data(request, await app.prisma.comment.update({ where: { id: comment.id }, data: { body: (request.body as any).body.trim() } })); });
  app.delete('/tasks/:taskId/comments/:commentId', { schema: { tags: ['Comments'], params: childParams('commentId'), security: [{ bearerAuth: [] }] } }, async (request, reply) => { const membership = await app.requireWorkspace(request); const p = request.params as any; await taskInWorkspace(app.prisma, membership.id, p.taskId); const comment = await app.prisma.comment.findFirst({ where: { id: p.commentId, taskId: p.taskId, deletedAt: null } }); if (!comment) throw notFound('Comment'); if (comment.authorId !== request.authUser.id && !['OWNER', 'ADMIN'].includes(membership.role)) throw forbidden(); await app.prisma.comment.update({ where: { id: comment.id }, data: { deletedAt: new Date() } }); return sendNoContent(reply); });
  app.get('/tasks/:taskId/attachments', { schema: { tags: ['Attachments'], params: taskParams, security: [{ bearerAuth: [] }] } }, async (request) => { const { id } = await app.requireWorkspace(request); const { taskId } = request.params as any; await taskInWorkspace(app.prisma, id, taskId); return data(request, await app.prisma.attachment.findMany({ where: { taskId }, include: { uploadedBy: { select: { id: true, name: true, avatarUrl: true } } }, orderBy: { createdAt: 'desc' } })); });
  app.post('/tasks/:taskId/attachments', { schema: { tags: ['Attachments'], params: taskParams, security: [{ bearerAuth: [] }], consumes: ['multipart/form-data'] } }, async (request, reply) => { const { id } = await app.requireWorkspace(request, ['OWNER', 'ADMIN', 'MEMBER']); const task = await taskInWorkspace(app.prisma, id, (request.params as any).taskId); const file = await request.file(); if (!file) throw notFound('File'); const key = `${randomUUID()}${extname(file.filename).toLowerCase().slice(0, 12)}`; const stored = await app.storage.save(key, file.file); const attachment = await app.prisma.attachment.create({ data: { taskId: task.id, uploadedById: request.authUser.id, filename: file.filename.slice(0, 255), mimeType: file.mimetype.slice(0, 120), size: file.file.bytesRead, storageKey: key, url: stored.url } }); return reply.code(201).send(data(request, attachment)); });
  app.delete('/tasks/:taskId/attachments/:attachmentId', { schema: { tags: ['Attachments'], params: childParams('attachmentId'), security: [{ bearerAuth: [] }] } }, async (request, reply) => { const membership = await app.requireWorkspace(request); const p = request.params as any; await taskInWorkspace(app.prisma, membership.id, p.taskId); const attachment = await app.prisma.attachment.findFirst({ where: { id: p.attachmentId, taskId: p.taskId } }); if (!attachment) throw notFound('Attachment'); if (attachment.uploadedById !== request.authUser.id && !['OWNER', 'ADMIN'].includes(membership.role)) throw forbidden(); await app.storage.delete(attachment.storageKey); await app.prisma.attachment.delete({ where: { id: attachment.id } }); return sendNoContent(reply); });
};
export default routes;
